[prop]
id = "KamModuleXTEST"
name = "Example Module Name"
version = "1.0.0"
versionCode = 1765548765937
author = "Your Name"
description = "Describe your module here"
updateJson = ""
metamodule = false

[mmrl.repo]
license = "MIT"
license_file = "LICENSE"
homepage = ""
readme = ""
readme_file = "README.md"
changelog = ""
changelog_file = "CHANGELOG.md"
screenshots = []
categories = ["tools"]
keywords = [
    "kam",
    "module",
    "android",
    "template",
]
maintainers = []
repository = ""
documentation = ""
issues = ""
funding = "https://github.com/sponsors/LIghtJUNction"
support = ""
donate = ""
cover = ""
icon = "icon.png"
devices = []
arch = ["arm64-v8a"]
require = []
antifeatures = []
max_num = 0
min_api = 21
max_api = 35
verified = false
features = [
    "module-template",
    "customization",
]

[mmrl.repo.note]
title = ""
message = ""

[mmrl.repo.manager.magisk]
devices = []
arch = []
require = []

[mmrl.repo.manager.kernelsu]
devices = []
arch = []
require = []

[mmrl.repo.manager.apatch]
devices = []
arch = []
require = []

[mmrl.repo.options.archive]
compression = ""

[kam]
min_api = 0
max_api = 0
supported_arch = []
conflicts = []
module_type = "kam"

[kam.build]
target_dir = "dist"
output_file = "{{id}}"
hooks_dir = "hooks"

[kam.tmpl.variables.repository]
var_type = "string"
required = false
default = ""

[kam.workspace]
members = ["."]

[tool]
